### ISSUE TITLE
[Chore] npm install issues

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/contoso-real-estate#386]
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [X ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
I believe some of this is warning and some is error (Azure function core tools). As I noted elsewhere, I think there is something wrong with Azure Functions core tools so this error is probably more concrete about the issue. Please leave this issue open, I'll cross reference on my issue post to Azure function core tools. 

**To Reproduce**

1. Fork from main
2. Open in Codespaces
3. npm install

**Expected behavior**
There is alot going on here. I think the Apollo stuff should be separate and lower pri. 

```
@dfberry ➜ /workspaces/contoso-real-estate (main) $ npm install
npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated apollo-datasource@3.3.2: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-plugin-base@3.7.2: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-errors@3.3.1: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-types@3.8.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated apollo-server-koa@3.10.0: The `apollo-server-koa` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-env@4.2.1: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-reporting-protobuf@3.4.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated @wessberg/ts-evaluator@0.0.27: this package has been renamed to ts-evaluator. Please install ts-evaluator instead
npm WARN deprecated apollo-server-core@3.12.1: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/workspaces/contoso-real-estate/packages/api-v4/node_modules/azure-functions-core-tools'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'listenercount'
npm ERR! Require stack:
npm ERR! - /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js
npm ERR! - /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/lib/install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js:3:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js',
npm ERR!     '/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/lib/install.js'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.15.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-10-18T17_43_12_284Z-debug-0.log
```

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version:
- Node.js version:
- output of `azd version`:

**Additional context**
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1517008/27738a9a-0c5a-4f2c-ae8a-7d3c35bbea24)

**Comment by dfberry** [comment]
Deployment fails from Codespaces 

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1517008/38e3d87e-1f48-468e-91a7-5d8cd3151558)

@dfberry ➜ /workspaces/contoso-real-estate (main) $ azd deploy

Deploying services (azd deploy)

  (x) Failed: Deploying service api

ERROR: failed restoring service 'api': failing invoking action 'restore', failed to install project /workspaces/contoso-real-estate/packages/api: exit code: 1, stdout: , stderr: npm ERR! code 1
npm ERR! path /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'listenercount'
npm ERR! Require stack:
npm ERR! - /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js
npm ERR! - /workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/lib/install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js:3:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/node_modules/unzipper/unzip.js',
npm ERR!     '/workspaces/contoso-real-estate/node_modules/azure-functions-core-tools/lib/install.js'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.15.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-10-18T19_32_13_169Z-debug-0.log

**Comment by glaucia86** [comment]
@dfberry hi! Can I close this issue?

**Comment by dfberry** [comment]
Yes - it hasn't happened in a while.
